ALTER SESSION SET CONTAINER = PDB_FORMATION;
CREATE TABLESPACE TS_ADMIN DATAFILE 'ts_admin1.dbf' SIZE 100M AUTOEXTEND ON;


CREATE TABLESPACE TS_APP DATAFILE 'ts_app1.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 200M;
CREATE TABLESPACE TS_DATA DATAFILE 'ts_data1.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 200M;
CREATE TABLESPACE TS_AI DATAFILE 'ts_ai1.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 200M;
CREATE TABLESPACE TS_CYBER DATAFILE 'ts_cyber1.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 200M;
CREATE TABLESPACE TS_UIUX DATAFILE 'ts_uiux1.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 200M;

COMMIT;


