CREATE TABLESPACE TS_ADMIN DATAFILE 'ts_admin.dbf' SIZE 100M AUTOEXTEND ON;


CREATE TABLESPACE TS_APP DATAFILE 'ts_app.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 200M;
CREATE TABLESPACE TS_DATA DATAFILE 'ts_data.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 200M;
CREATE TABLESPACE TS_AI DATAFILE 'ts_ai.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 200M;
CREATE TABLESPACE TS_CYBER DATAFILE 'ts_cyber.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 200M;
CREATE TABLESPACE TS_UIUX DATAFILE 'ts_uiux.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 200M;

COMMIT;